### PR TITLE
Disconnect Update

### PR DESCRIPTION
**Pull request by CarlJMcGee**
Added a couple of events, methods, and hooks related to the disconnection for the dice.

- `connected` die property and `useConnectionStatus()` React hook
- `onDisconnect` event sets connected property to false
- `disconnect()` method disconnects die
- `removeDie()` function added to `useDiceSet()` return array
- fixed gatt error when `getBatteryLevel()` method calls for battery level when die is disconnected

### CODE REVIEW

**Comment by Zeragamba** [comment]
issue: `package-lock.json` file should be removed

**Comment by Zeragamba** [comment]
question: I see that yarn.lock was upated, was there a dependacy update?

**Comment by CarlJMcGee** [comment]
I don't think so. At least I didn't intentionally. Let me take a look.

**Comment by CarlJMcGee** [comment]
I double checked all of the project dependencies and it should be all the same. I'll revert the yarn.lock.

**Comment by CarlJMcGee** [comment]
Sorry I don't use Yarn and am not familiar with with it, so I am not sure what i did to change the `yarn.lock`. All package dependencies are the same.

**Comment by Zeragamba** [comment]
Thanks for the PR! Merged :)

**Pull request merged**
